on: [push]
jobs:
  baseCall:
    uses: dstrebul-sym/symverse-infra/.github/workflows/base.yml@master
  deploy:
    runs-on: symverse-deploy
    container:
      image: proget.repo.symbotic.corp/dev_images/library/symverse-deploy:v2.1.2
      env:
        DEPLOYMENT_RELEASE: test
        DEPLOYMENT_NAMESPACE: sandbox
        KUBECONFIG: "/root/.kube/config"
        KUBE_FILE: ${{ secrets.KUBECONFIG_DEV_SECRET }}
        DEPLOYMENT_FOLDER: test
    steps:
      - name: Checkout repo 
        run: |
             rm -rf deploy
             git clone https://github.com/dstrebul-sym/symverse-deployment.git deploy
             cd deploy
             git status
             git pull
      - run: echo "Deploy test"
        name: "Echo test"
      - name: "kube availability test"
        run: |
             mkdir -p /root/.kube
             echo -n "$KUBE_FILE" > $KUBECONFIG
             kubectl version
             helm version
             helm2 version || true
      - name: "helm repos update"
        run: |
             helm repo add incubator https://charts.helm.sh/incubator --debug
             helm repo add stable https://charts.helm.sh/stable
             helm repo add symbotic https://proget.repo.symbotic.corp/helm/SymboticHelm/
             helm repo add third https://proget.repo.symbotic.corp/helm/Third-Party-Helm/
             helm repo add fluent https://fluent.github.io/helm-charts
             helm repo add elastic https://helm.elastic.co
             helm repo update
      - name: "service deploy"
        run: |
             cd deploy
             git diff HEAD~1
             python3 /scripts/deploy.py \
             --folder ${DEPLOYMENT_FOLDER} \
             --name ${DEPLOYMENT_RELEASE} \
             --namespace ${DEPLOYMENT_NAMESPACE} \
             --args -f common/values.yaml -f ${DEPLOYMENT_FOLDER}/values.yaml
        

