name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Service name'
        default: 'sym-cad-api'
        required: true
        type: string

jobs:
  baseCall:
    uses: dstrebul-sym/symverse-infra/.github/workflows/PrintServiceName.yml@master
    with:
        service: ${{ inputs.name }}
